baseURL = "https://arawles.co.uk"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Adam Rawles"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "I'm Adam Rawles"
author = "Adam Rawles"
description = "R programmer and analyst"
profilePicture = "images/profile.jpg"
keywords = ""
#favicon = "favicons/"
customJs = []
#images = ["images/site-feature-image.png"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/adam-rawles-40412911b/?originalSubdomain=uk"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/ARawles"


[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:adamrawles@hotmail.co.uk"

## Menu items

[menu]

  
  [[menu.main]]
  name = "About"
  weight = 200
  identifier = "about"
  url = "/about"
  
  [[menu.main]]
  name = "CV"
  weight = 300
  identifier = "cv"
  url = "/cv.html"

  [[menu.main]]
  name = "BMRSr"
  weight = 400
  identifier = "bmrsr"
  url = "https://bmrsr.arawles.co.uk"
  
  [[menu.main]]
  name = "faviconR"
  weight = 500
  identifier = "faviconr"
  url = "https://faviconr.arawles.co.uk"
  
  [[menu.main]]
  name = "teacheR"
  weight = 600
  identifier = "teacher"
  url = "https://teacher.arawles.co.uk"


  [[menu.main]]
  name = "opeRate"
  weight = 700
  identifier = "operate"
  url = "https://operate.arawles.co.uk"

